### PR TITLE
Import sandhose/prettier-animated-logo

### PR DESCRIPTION
**Pull request by sandhose**
I imported the repo with a fake merge commit + `git read-tree` to have the whole history.

I also published the package under `prettier-logo`

cc @azz

### CODE REVIEW

**Comment by lipis** [comment]
We should still squash the commits before merging to the master though.. otherwise it's too much noise.

**Comment by lipis** [comment]
Is this one OK to merge? @azz @sandhose

**Comment by sandhose** [comment]
I thought it was already merged. Go for it! 👍

**Comment by lipis** [comment]
Thanks @sandhose!

**Pull request merged**
